require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailingAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # MailingAddress. As you add validations to MailingAddress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "address_01" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailingAddressesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mailing_addresses as @mailing_addresses" do
      mailing_address = MailingAddress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mailing_addresses).should eq([mailing_address])
    end
  end

  describe "GET show" do
    it "assigns the requested mailing_address as @mailing_address" do
      mailing_address = MailingAddress.create! valid_attributes
      get :show, {:id => mailing_address.to_param}, valid_session
      assigns(:mailing_address).should eq(mailing_address)
    end
  end

  describe "GET new" do
    it "assigns a new mailing_address as @mailing_address" do
      get :new, {}, valid_session
      assigns(:mailing_address).should be_a_new(MailingAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested mailing_address as @mailing_address" do
      mailing_address = MailingAddress.create! valid_attributes
      get :edit, {:id => mailing_address.to_param}, valid_session
      assigns(:mailing_address).should eq(mailing_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MailingAddress" do
        expect {
          post :create, {:mailing_address => valid_attributes}, valid_session
        }.to change(MailingAddress, :count).by(1)
      end

      it "assigns a newly created mailing_address as @mailing_address" do
        post :create, {:mailing_address => valid_attributes}, valid_session
        assigns(:mailing_address).should be_a(MailingAddress)
        assigns(:mailing_address).should be_persisted
      end

      it "redirects to the created mailing_address" do
        post :create, {:mailing_address => valid_attributes}, valid_session
        response.should redirect_to(MailingAddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mailing_address as @mailing_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailingAddress.any_instance.stub(:save).and_return(false)
        post :create, {:mailing_address => { "address_01" => "invalid value" }}, valid_session
        assigns(:mailing_address).should be_a_new(MailingAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailingAddress.any_instance.stub(:save).and_return(false)
        post :create, {:mailing_address => { "address_01" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mailing_address" do
        mailing_address = MailingAddress.create! valid_attributes
        # Assuming there are no other mailing_addresses in the database, this
        # specifies that the MailingAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MailingAddress.any_instance.should_receive(:update_attributes).with({ "address_01" => "MyString" })
        put :update, {:id => mailing_address.to_param, :mailing_address => { "address_01" => "MyString" }}, valid_session
      end

      it "assigns the requested mailing_address as @mailing_address" do
        mailing_address = MailingAddress.create! valid_attributes
        put :update, {:id => mailing_address.to_param, :mailing_address => valid_attributes}, valid_session
        assigns(:mailing_address).should eq(mailing_address)
      end

      it "redirects to the mailing_address" do
        mailing_address = MailingAddress.create! valid_attributes
        put :update, {:id => mailing_address.to_param, :mailing_address => valid_attributes}, valid_session
        response.should redirect_to(mailing_address)
      end
    end

    describe "with invalid params" do
      it "assigns the mailing_address as @mailing_address" do
        mailing_address = MailingAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailingAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => mailing_address.to_param, :mailing_address => { "address_01" => "invalid value" }}, valid_session
        assigns(:mailing_address).should eq(mailing_address)
      end

      it "re-renders the 'edit' template" do
        mailing_address = MailingAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailingAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => mailing_address.to_param, :mailing_address => { "address_01" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mailing_address" do
      mailing_address = MailingAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => mailing_address.to_param}, valid_session
      }.to change(MailingAddress, :count).by(-1)
    end

    it "redirects to the mailing_addresses list" do
      mailing_address = MailingAddress.create! valid_attributes
      delete :destroy, {:id => mailing_address.to_param}, valid_session
      response.should redirect_to(mailing_addresses_url)
    end
  end

end
