require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ResidentialAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # ResidentialAddress. As you add validations to ResidentialAddress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "address_01" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ResidentialAddressesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all residential_addresses as @residential_addresses" do
      residential_address = ResidentialAddress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:residential_addresses).should eq([residential_address])
    end
  end

  describe "GET show" do
    it "assigns the requested residential_address as @residential_address" do
      residential_address = ResidentialAddress.create! valid_attributes
      get :show, {:id => residential_address.to_param}, valid_session
      assigns(:residential_address).should eq(residential_address)
    end
  end

  describe "GET new" do
    it "assigns a new residential_address as @residential_address" do
      get :new, {}, valid_session
      assigns(:residential_address).should be_a_new(ResidentialAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested residential_address as @residential_address" do
      residential_address = ResidentialAddress.create! valid_attributes
      get :edit, {:id => residential_address.to_param}, valid_session
      assigns(:residential_address).should eq(residential_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ResidentialAddress" do
        expect {
          post :create, {:residential_address => valid_attributes}, valid_session
        }.to change(ResidentialAddress, :count).by(1)
      end

      it "assigns a newly created residential_address as @residential_address" do
        post :create, {:residential_address => valid_attributes}, valid_session
        assigns(:residential_address).should be_a(ResidentialAddress)
        assigns(:residential_address).should be_persisted
      end

      it "redirects to the created residential_address" do
        post :create, {:residential_address => valid_attributes}, valid_session
        response.should redirect_to(ResidentialAddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved residential_address as @residential_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResidentialAddress.any_instance.stub(:save).and_return(false)
        post :create, {:residential_address => { "address_01" => "invalid value" }}, valid_session
        assigns(:residential_address).should be_a_new(ResidentialAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResidentialAddress.any_instance.stub(:save).and_return(false)
        post :create, {:residential_address => { "address_01" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested residential_address" do
        residential_address = ResidentialAddress.create! valid_attributes
        # Assuming there are no other residential_addresses in the database, this
        # specifies that the ResidentialAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ResidentialAddress.any_instance.should_receive(:update_attributes).with({ "address_01" => "MyString" })
        put :update, {:id => residential_address.to_param, :residential_address => { "address_01" => "MyString" }}, valid_session
      end

      it "assigns the requested residential_address as @residential_address" do
        residential_address = ResidentialAddress.create! valid_attributes
        put :update, {:id => residential_address.to_param, :residential_address => valid_attributes}, valid_session
        assigns(:residential_address).should eq(residential_address)
      end

      it "redirects to the residential_address" do
        residential_address = ResidentialAddress.create! valid_attributes
        put :update, {:id => residential_address.to_param, :residential_address => valid_attributes}, valid_session
        response.should redirect_to(residential_address)
      end
    end

    describe "with invalid params" do
      it "assigns the residential_address as @residential_address" do
        residential_address = ResidentialAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResidentialAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => residential_address.to_param, :residential_address => { "address_01" => "invalid value" }}, valid_session
        assigns(:residential_address).should eq(residential_address)
      end

      it "re-renders the 'edit' template" do
        residential_address = ResidentialAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResidentialAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => residential_address.to_param, :residential_address => { "address_01" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested residential_address" do
      residential_address = ResidentialAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => residential_address.to_param}, valid_session
      }.to change(ResidentialAddress, :count).by(-1)
    end

    it "redirects to the residential_addresses list" do
      residential_address = ResidentialAddress.create! valid_attributes
      delete :destroy, {:id => residential_address.to_param}, valid_session
      response.should redirect_to(residential_addresses_url)
    end
  end

end
